const easier_contacts_view_query = "DROP VIEW IF EXISTS easier_contacts_view; CREATE VIEW IF NOT EXISTS easier_contacts_view AS  SELECT      jid,      (          SELECT              CASE                  WHEN MIN(display_name) IS NULL THEN '+' || SUBSTR(jid, 1, INSTR(jid, '@') - 1)                  ELSE MIN(DISPLAY_NAME)              END      ) display_name,      (          SELECT              CASE                  WHEN jid LIKE '%g.us' THEN 1                  ELSE 0              END      ) is_group,      (          SELECT              conversation_message_count          FROM              wa_contact_storage_usage wacsu2          WHERE              wacsu2.jid = wa_contacts.jid      ) messages_count  FROM      wa_contacts  WHERE      EXISTS (          SELECT              1          FROM              wa_contact_storage_usage wacsu          where              wacsu.jid = wa_contacts.jid      )  GROUP BY      jid;"
const easier_message_view_query = "DROP VIEW IF EXISTS easier_messages_view; CREATE VIEW IF NOT EXISTS easier_messages_view AS  SELECT      message._id message_row_id,      chat_view.raw_string_jid jid,      text_data,      from_me,      timestamp,      CASE          WHEN message.message_type = 0 THEN 'text'          WHEN message.message_type = 1 THEN 'image'          WHEN message.message_type = 2 THEN 'voice_note'          WHEN message.message_type = 3 THEN 'video'          WHEN message.message_type = 4 THEN 'contact'          WHEN message.message_type = 5 THEN 'location'          WHEN message.message_type = 9 THEN 'document'          WHEN message.message_type = 13 THEN 'gif'          WHEN message.message_type = 15 THEN 'voice_note'          WHEN message.message_type = 15 THEN 'voice_note'          WHEN message.message_type = 42 THEN 'view_once_image'          WHEN message.message_type = 43 THEN 'view_once_video'          WHEN message.message_type = 66 THEN 'poll'          ELSE 'unknown: ' || CAST(message.message_type AS TEXT)      END message_type  FROM      message      LEFT JOIN chat_view ON chat_view._id = message.chat_row_id;"
const get_some_messages = "SELECT * FROM easier_messages_view m LEFT JOIN easier_contacts_view c ON c.jid = m.jid WHERE c.display_name=:from_who and m.message_type='text' LIMIT 10";

export const queries = {
    easier_contacts_view_query,
    easier_message_view_query,
    get_some_messages
}

